version: "3.8"

networks:
    wvv:


services:
    nginx:
        container_name: nginx
        image: nginx:stable-alpine
        # restart: always

        ports:
            # - 80:80
            - 40:40

        volumes:
            - ./conf/nginx.conf:/etc/nginx/nginx.conf

        networks:
            - wvv


    frontend-wvv:
        container_name: frontend-wvv
        build:
            dockerfile: etc/frontend.Dockerfile
            context: .
        ports:
            - 3000:3000
        depends_on:
            - nginx
        networks:
            - wvv

